# Generated by Django 3.2.22 on 2023-10-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Culvers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Ordering',
        ),
    ]
